from durator.world.game.skill.constants import SkillId


# Store max level and max stat level for each known skill.
SKILL_MAX_LEVELS = {

    SkillId.COMBAT:                (   5, 0 ),
    SkillId.SUBTLETY:              (   5, 0 ),
    SkillId.POISONS:               (   5, 0 ),
    SkillId.SWORDS:                (   5, 0 ),
    SkillId.BOWS:                  (   5, 0 ),
    SkillId.MACES:                 (   5, 0 ),
    SkillId.GUNS:                  (   5, 0 ),
    SkillId.DEFENSE:               (   5, 0 ),
    SkillId.LANGUAGE_ORCISH:       ( 300, 0 ),
    SkillId.LANGUAGE_DWARVEN:      (   0, 0 ),
    SkillId.LANGUAGE_DARNASSIAN:   (   0, 0 ),
    SkillId.LANGUAGE_TAURAHE:      (   0, 0 ),
    SkillId.DUAL_WIELD:            (   0, 0 ),
    SkillId.FIRST_AID:             (   0, 0 ),
    SkillId.LANGUAGE_THALASSIAN:   (   0, 0 ),
    SkillId.LANGUAGE_DRACONIC:     (   0, 0 ),
    SkillId.LANGUAGE_DEMON_TONGUE: (   0, 0 ),
    SkillId.LANGUAGE_TITAN:        (   0, 0 ),
    SkillId.LANGUAGE_OLD_TONGUE:   (   0, 0 ),
    SkillId.SURVIVAL:              (   1, 0 ),
    SkillId.HORSE_RIDING:          (   0, 0 ),
    SkillId.WOLF_RIDING:           (   0, 0 ),
    SkillId.TIGER_RIDING:          (   0, 0 ),
    SkillId.RAM_RIDING:            (   0, 0 ),
    SkillId.UNARMED:               (   5, 0 ),
    SkillId.BLACKSMITHING:         (   0, 0 ),
    SkillId.LEATHERWORKING:        (   0, 0 ),
    SkillId.ALCHEMY:               (   0, 0 ),
    SkillId.DAGGERS:               (   5, 0 ),
    SkillId.THROWN:                (   5, 0 ),
    SkillId.HERBALISM:             (   0, 0 ),
    SkillId.GENERIC_DND:           (   5, 0 ),
    SkillId.COOKING:               (   0, 0 ),
    SkillId.MINING:                (   0, 0 ),
    SkillId.TAILORING:             (   0, 0 ),
    SkillId.ENGINEERING:           (   0, 0 ),
    SkillId.RACIAL_UNDEAD:         (   5, 0 ),
    SkillId.CROSSBOWS:             (   5, 0 ),
    SkillId.ASSASSINATION:         (   5, 0 ),
    SkillId.LANGUAGE_GNOMISH:      (   0, 0 ),
    SkillId.LANGUAGE_TROLL:        (   0, 0 ),
    SkillId.ENCHANTING:            (   0, 0 ),
    SkillId.FISHING:               (   0, 0 ),
    SkillId.SKINNING:              (   0, 0 ),
    SkillId.LEATHER:               (   1, 0 ),
    SkillId.CLOTH:                 (   1, 0 ),
    SkillId.FIST_WEAPONS:          (   1, 0 ),
    SkillId.RAPTOR_RIDING:         (   0, 0 ),
    SkillId.UNDEAD_HORSEMANSHIP:   (   0, 0 ),
    SkillId.LOCKPICKING:           (   5, 0 ),
    SkillId.LANGUAGE_GUTTERSPEAK:  ( 300, 0 ),
    SkillId.KODO_RIDING:           (   0, 0 ),
    SkillId.JEWELCRAFTING:         (   0, 0 )

}
