from durator.world.game.skill.constants import SkillIdent


# Store max level and max stat level for each known skill.
SKILL_MAX_LEVELS = {

    SkillIdent.COMBAT:                (   5, 0 ),
    SkillIdent.SUBTLETY:              (   5, 0 ),
    SkillIdent.POISONS:               (   5, 0 ),
    SkillIdent.SWORDS:                (   5, 0 ),
    SkillIdent.BOWS:                  (   5, 0 ),
    SkillIdent.MACES:                 (   5, 0 ),
    SkillIdent.GUNS:                  (   5, 0 ),
    SkillIdent.DEFENSE:               (   5, 0 ),
    SkillIdent.LANGUAGE_ORCISH:       ( 300, 0 ),
    SkillIdent.LANGUAGE_DWARVEN:      (   0, 0 ),
    SkillIdent.LANGUAGE_DARNASSIAN:   (   0, 0 ),
    SkillIdent.LANGUAGE_TAURAHE:      (   0, 0 ),
    SkillIdent.DUAL_WIELD:            (   0, 0 ),
    SkillIdent.FIRST_AID:             (   0, 0 ),
    SkillIdent.LANGUAGE_THALASSIAN:   (   0, 0 ),
    SkillIdent.LANGUAGE_DRACONIC:     (   0, 0 ),
    SkillIdent.LANGUAGE_DEMON_TONGUE: (   0, 0 ),
    SkillIdent.LANGUAGE_TITAN:        (   0, 0 ),
    SkillIdent.LANGUAGE_OLD_TONGUE:   (   0, 0 ),
    SkillIdent.SURVIVAL:              (   1, 0 ),
    SkillIdent.HORSE_RIDING:          (   0, 0 ),
    SkillIdent.WOLF_RIDING:           (   0, 0 ),
    SkillIdent.TIGER_RIDING:          (   0, 0 ),
    SkillIdent.RAM_RIDING:            (   0, 0 ),
    SkillIdent.UNARMED:               (   5, 0 ),
    SkillIdent.BLACKSMITHING:         (   0, 0 ),
    SkillIdent.LEATHERWORKING:        (   0, 0 ),
    SkillIdent.ALCHEMY:               (   0, 0 ),
    SkillIdent.DAGGERS:               (   5, 0 ),
    SkillIdent.THROWN:                (   5, 0 ),
    SkillIdent.HERBALISM:             (   0, 0 ),
    SkillIdent.GENERIC_DND:           (   5, 0 ),
    SkillIdent.COOKING:               (   0, 0 ),
    SkillIdent.MINING:                (   0, 0 ),
    SkillIdent.TAILORING:             (   0, 0 ),
    SkillIdent.ENGINEERING:           (   0, 0 ),
    SkillIdent.RACIAL_UNDEAD:         (   5, 0 ),
    SkillIdent.CROSSBOWS:             (   5, 0 ),
    SkillIdent.ASSASSINATION:         (   5, 0 ),
    SkillIdent.LANGUAGE_GNOMISH:      (   0, 0 ),
    SkillIdent.LANGUAGE_TROLL:        (   0, 0 ),
    SkillIdent.ENCHANTING:            (   0, 0 ),
    SkillIdent.FISHING:               (   0, 0 ),
    SkillIdent.SKINNING:              (   0, 0 ),
    SkillIdent.LEATHER:               (   1, 0 ),
    SkillIdent.CLOTH:                 (   1, 0 ),
    SkillIdent.FIST_WEAPONS:          (   1, 0 ),
    SkillIdent.RAPTOR_RIDING:         (   0, 0 ),
    SkillIdent.UNDEAD_HORSEMANSHIP:   (   0, 0 ),
    SkillIdent.LOCKPICKING:           (   5, 0 ),
    SkillIdent.LANGUAGE_GUTTERSPEAK:  ( 300, 0 ),
    SkillIdent.KODO_RIDING:           (   0, 0 ),
    SkillIdent.JEWELCRAFTING:         (   0, 0 )

}
